name: courtyard-artifact
recipe: lamp
config:
  webroot: .
  php: 7.3

services:
  appserver:
    build_as_root:
      - apt-get install gcc g++ make
      - curl -sL https://deb.nodesource.com/setup_13.x | bash
      - apt-get install -y nodejs
      - apt-get install -y npm
      - nodejs -v
tooling:
  clone:
    description: Clone Courtyard to build an artifact, or for development. `lando clone [branch]`
    service: appserver
    cmd: scripts/clone.sh
  artifact:
    description: (Re)build the artifact.
    cmd:
      - appserver: composer install -d /app/courtyard/
      - appserver: composer run generate -d /app/courtyard
      - appserver: npm install --prefix /app/courtyard/ && npm run build --prefix /app/courtyard/
      - appserver: composer run artifact-sync -d /app
  sync:
    description: Sync built assets to artifact.
    service: appserver
    cmd: composer run artifact-sync -d /app
  node:
    service: appserver
  npm:
    service: appserver
