name: build-artifact-dev
on: [ repository_dispatch, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v2
        with:
          node-version: "12.22.7"
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
      # Build the 2.x-dev artifact.
      - uses: actions/checkout@v2
        with:
          repository: JudicialCouncilOfCalifornia/courtyard
          path: courtyard
          ref: 2.x-dev
      - run: |
          cd courtyard
          composer install
          npm install
          npm run build
      - run: |
          mkdir -p 2.x-dev/public 2.x-dev/source/_patterns
          rm -rf 2.x-dev/public/* 2.x-dev/source/_patterns/*
          cp -R courtyard/public/* 2.x-dev/public/
          cp -R courtyard/source/_patterns/* 2.x-dev/source/_patterns/
          rm -rf courtyard
      - uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        with:
          source_dir: 2.x-dev
          container_name: $web
          connection_string: ${{ secrets.ConnectionString }}
          extra_args: --destination 2.xdev          
          sync: false  
